import React from "react";

const AboutPage: React.FunctionComponent = () => {
  const [actionSheetOpened, setActionSheetOpened] = React.useState(false);

  return (
    <div className="page">
      <div className="section-container">
        <p>This mini app was generated by zmp-cli</p>
      </div>
      <div>
        <button
          variant='secondary'
          fullWidth
          onClick={() => setActionSheetOpened(true)}
        >
          Back
        </button>
      </div>
    </div>
  );
};

export default AboutPage;